/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'ai' : null } |
  { 'formation' : null } |
  { 'education' : null };
export interface Course {
  'id' : bigint,
  'title' : string,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'description' : string,
  'category' : Category,
}
export interface Testimonial {
  'id' : bigint,
  'name' : string,
  'role' : string,
  'message' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getCoursesByCategory' : ActorMethod<[Category], Array<Course>>,
  'subscribeToNewsletter' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];