/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'ai' : IDL.Null,
  'formation' : IDL.Null,
  'education' : IDL.Null,
});
export const Course = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'category' : Category,
});
export const Testimonial = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'message' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
  'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'ai' : IDL.Null,
    'formation' : IDL.Null,
    'education' : IDL.Null,
  });
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'category' : Category,
  });
  const Testimonial = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'message' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getCoursesByCategory' : IDL.Func([Category], [IDL.Vec(Course)], ['query']),
    'subscribeToNewsletter' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };